name: Windows

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        node: ['20', '18', '16']

    name: Node v${{ matrix.node }}
    steps:
      - name: Configure git line-breaks
        run: git config --global core.autocrlf false

      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install pnpm
        run: npm install pnpm -g

      - name: pnpm install
        run: pnpm install --ignore-scripts

      - name: run tests
        run: pnpm --filter "...[origin/master]" ci:test
